### ISSUE TITLE
[CHORE]: Cachez ces credentials que je ne saurais voir

### ISSUE THREAD

**Issue by bero-semifir** [mick-sudo/localib-back#3]
Passe par un .env pour masquer tes infos de connexion à la base de données.

Ca permet aussi d'externaliser les variables de ton app.

[https://docs.nestjs.com/techniques/configuration#getting-started](https://docs.nestjs.com/techniques/configuration#getting-started)

**Comment by Gabou00** [comment]
La base

**Comment by mick-sudo** [comment]
done
